version: '3'

services:
  web:
    build:
      context: . #in which directory to do the build.
      dockerfile: Dockerfile.dev #which file to use to build image
    ports: 
     - "3000:3000"
    volumes:
     - /app/node_modules #add node_mdoules
     - .:/app #map current directory to app in container