version: '3'
# services means a type of container
# create containers
# The below will create images within the same network.
services:
  redis-server:
    image: redis # find image from cache/dockerhub
  node-app:
    build: . # create image from building Dockerfile current directory.
    restart: always # restart policy | always - restart if container stops | "no" - never restart (default) | on-failure - restart on error | unless-stopped - restart unless force stopped by me/dev
    ports:
     - "4001:8081" # map machine port 4001 to container 8081

# docker-compose up - runs images in yaml file
# docker-compose up --build - rebuilds and runs images in yaml file.
# docker-compose down - stop containers
# docker-compose ps - looks for containers in a docker-compose.yml file